### ISSUE TITLE
Links in documents dont work

### ISSUE THREAD

**Issue by antonilol** [nickmonad/bips-dev#2]
go to https://bips.dev/341/ under 'Script validation rules' and click the link to BIP141 and BIP340. maybe this applies to other links too

**Comment by delta1** [comment]
Noticed this too, then saw this in the readme 

> a few things are broken. Tables seem to be the biggest problem, with internal links and code snippets being a close second

**Comment by nickmonad** [comment]
I _think_ this is a relatively easy fix. Hopefully I'll find time to address this soon, this project has fallen off my radar recently, but I'm glad people are using it!

**Comment by delta1** [comment]
If you give me a pointer I'll take a look! The site has definitely been useful to me, so I'd love to help

**Comment by nickmonad** [comment]
Ok, actually, now I remember why this is difficult in the current setup.

In the primary `process` function here: https://github.com/nickmonad/bips-dev/blob/master/src/bip.rs#L13, only the "front matter" is parsed directly into an in-memory structure we can use to format the front matter required by zola.

The rest of the markdown parsing/conversion relies on a shell call to `pandoc`, so I think to do this correctly, we'd have to traverse the whole mediawiki content tree and rewrite these BIP links so they are absolute to the root of the site, 
i.e. `bip-0141.mediawiki` is rendered as `/141`

And at that point, it's probably worth it to attempt rendering the entire mediawiki document into markdown and not rely on pandoc at all. I recall that was something I had originally thought about doing, but wanted to get something up and running quickly. It would be a fair amount of work, but might be worth it in the end, so there is more control over how the BIPs look on the final render. Currently, there are other rendering issues that technically work, but aren't great, like tables and some odd code blocks here and there.

Another (long shot) option might be some kind of pandoc extension? (If they support it.) If we could capture every point it finds a hyperlink and override the result, that would be easier. Again, assuming something like that is even possible.

**Comment by nickmonad** [comment]
Or, maybe the best place to start is to just find and replace them with a regex match? That would truly be the easiest thing I think. The markdown index.md files prior to rendering through zola can be piped into a shell script with some fancy `sed` match and replace as part of the build process.

**Comment by nickmonad** [comment]
This should be resolved now. Feel free to re-open this if you find any instances where it's still broken.
